import React from "react";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { font_DM_Sans } from "@/Utils/Fonts/fonts";
import "../styles/globals.scss";
export const metadata = {
  title: "ShoesStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={font_DM_Sans.style}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
